export enum COMPATIBILITY {
    NONE = 'NONE',
    FULL = 'FULL',
    BACKWARD = 'BACKWARD',
    FORWARD = 'FORWARD',
    BACKWARD_TRANSITIVE = 'BACKWARD_TRANSITIVE',
    FORWARD_TRANSITIVE = 'FORWARD_TRANSITIVE',
    FULL_TRANSITIVE = 'FULL_TRANSITIVE',
}

export const DEFAULT_SEPERATOR = '.'


